# Generated by Django 2.2.2 on 2019-11-28 11:59

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('show_id', models.CharField(max_length=10, verbose_name='id')),
            ],
            options={
                'verbose_name': 'watchlist',
                'verbose_name_plural': 'watchlists',
                'ordering': ['-modified'],
            },
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['-modified'], name='api_watchli_modifie_2ee16c_idx'),
        ),
    ]
