# Generated by Django 2.2.2 on 2019-11-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='show_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='id'),
        ),
    ]
