# Generated by Django 2.2.2 on 2019-11-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191128_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='description',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='image',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='network',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='network'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='schedule',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='schedule'),
        ),
    ]
